name: "Tigo Proxy"
description: "Proxy for Tigo CCA to allow solar panel data to be collected"
version: "1.2.5"
slug: tigo_proxy
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
# journald: true
ports:
  1234/tcp: 8888
ports_description:
  1234/tcp: "The port for Tigo CCA to connect"
map:
  - homeassistant_config
options:
  tigo_server: ds205.tigoenergy.com
  tigo_port: 443
  max_read: 1024
schema:
  tigo_server: str
  tigo_port: int
  max_read: int
services:
  - mqtt:need